# Generated by Django 4.2.5 on 2023-09-15 08:32

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('srollno', models.CharField(max_length=20)),
                ('sdob', models.DateField()),
                ('sbg', models.CharField(max_length=20)),
                ('pgname', models.CharField(max_length=100)),
                ('pgphno', phone_field.models.PhoneField(max_length=31)),
                ('pgmail', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
