# Generated by Django 4.2.5 on 2023-09-15 14:50

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stureg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stureg',
            name='pgname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stureg',
            name='pgphno',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='stureg',
            name='sbg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stureg',
            name='sdob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='stureg',
            name='sname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stureg',
            name='srollno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
